default_index_setting:
  settings:
    index:
      number_of_shards : 5

index_mapping:
  users:
    mappings:
      user:
        properties:
          name:
            type: "string"
  statuses:
    mappings:
      status:

  workspaces:
    mappings:
      workspace:
        properties:
          entity_id:
            type: "string"
            index: "not_analyzed"
 
  scrapbooks:
    mappings:
      scrapbook:
        properties:
          user_id:
            type: "string"
            index: "not_analyzed"
 
  profiles:
    mappings:
      profile:
