default_index_setting:
  settings:
    index:
      number_of_shards : 5

index_mapping:
  users:
    mappings:
      user:
        properties:
          name:
            type: "string"
  statuses:
    mappings:
      status:

  workspaces:
    mappings:
      workspace:

  scrapbooks:
    mappings:
      scrapbook:

  profiles:
    mappings:
      profile:
